language: node_js
sudo: false
node_js:
  - lts/dubnium
  - node
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: VYO6mwMtWzQ0XtzWLaLldPseMyGRAE1LSUq5wPEZSm61qKvvE23WrZFd9Gw3jtsemFRirRaZEwjLpjtFbHpLKokogQ3AWLV7S28ToS+PruHtmnyLiIL+VPoBDau5YfJOx7UGoarBIjJuU955IP4FUL28RFvs43RaLpRUhB3z6j0=
  file:
    - 'brill.js'
    - 'brill.min.js'
  on:
    tags: true
